# fly.toml app configuration file generated for part6-3 on 2024-12-07T23:57:10+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'part6-3'
primary_region = 'fra'

[env]
  PORT = "3000"

[processes]
  web = "node server.js"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['web']


[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[deploy]
  strategy = "canary"